title: "Rishikesh Gajjala"
description: "Postdoc @ CQTS, quantum computing ∩ discrete algorithms"
baseurl: ""
url: "https://rishigajjala.github.io"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

nav:
  - Home: index.md
  - Research: research.md
  - Publications: publications.md

repository:
  url: "https://github.com/rishigajjala/rishigajjala.github.io"